#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /config/{crontabs,www/freshrss}

# create symlinks
symlinks=(
    /app/www/data
    /app/www/extensions
)

for i in "${symlinks[@]}"; do
    if [[ -e "$i" && ! -L "$i" ]]; then
        mv "$i" "${i}.bak"
    fi
    if [[ ! -L "$i" ]]; then
        ln -s "/config/www/freshrss/$(basename "$i")" "$i"
    fi
    if [[ ! -d "/config/www/freshrss/$(basename "$i")" ]]; then
        cp -R "${i}.bak" "/config/www/freshrss/$(basename "$i")"
    fi
done

# backwards compatibility
if grep -q 'root /config/www/freshrss/p;' /config/nginx/site-confs/default.conf; then
    cp /defaults/nginx/site-confs/default.conf.sample /config/nginx/site-confs/default.conf
fi

# disable updates
if [[ -f /config/www/freshrss/data/config.php ]]; then
    sed -i "s|'disable_update' => false,|'disable_update' => true,|g" /config/www/freshrss/data/config.php
fi

# set cronjob
if [[ ! -f /config/crontabs/root ]]; then
    cp /defaults/crontabs/root /config/crontabs/root
fi
sed -E -i "s|.*/freshrss/app/actualize_script.php.*|*/15    *       *       *       *       /usr/bin/php /app/www/app/actualize_script.php > /tmp/FreshRSS.log 2>\&1|" /config/crontabs/root
cp /config/crontabs/root /etc/crontabs/root

# permissions
lsiown -R abc:abc \
    /app/www \
    /config
