#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/www/freshrss

# create symlinks
symlinks=( \
/usr/share/webapps/freshrss/data \
/usr/share/webapps/freshrss/extensions )

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && mv "$i" "${i}.bak"
[[ ! -L "$i" ]] && ln -s "/config/www/freshrss/$(basename "$i")" "$i"
[[ ! -d "/config/www/freshrss/$(basename "$i")" ]] && \
	cp -R "${i}.bak" "/config/www/freshrss/$(basename "$i")"
done

# backwards compatibility
if grep -q 'root /config/www/freshrss/p;' /config/nginx/site-confs/default; then 
	cp /defaults/default /config/nginx/site-confs/default
fi

# set cronjob
crontab -u root /defaults/freshrss

# permissions
chown -R abc:abc \
	/usr/share/webapps/freshrss \
	/config
